apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: newsletter-ui
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: newsletter
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
  build:
    env:
      - name: BP_NODE_RUN_SCRIPTS
        value: "build"
      - name: BP_WEB_SERVER_ROOT
        value: "dist"
  source:
    git:
      url: https://github.com/sdubois-tapdemo/newsletter
      subPath: newsletter-ui
      ref:
        branch: main
