---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  annotations:
    autoscaling.knative.dev/minScale: "1"
  labels:
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/part-of: newsletter-subscription
    apps.tanzu.vmware.com/debug: "true"
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
  name: newsletter-subscription
  namespace: newsletter
spec:
  build:
    env:
    - name: BP_JVM_VERSION
      value: "20"
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: api_descriptor
    value:
      description: Newsletter Subscription Management REST API Service
      lifecycle: experimental
      location:
        path: /v3/api-docs
      owner: newsletter-team
      system: newsletter-subscription
      type: openapi
  - name: gitops_ssh_secret
    value: git-secret
  - name: gitops_repository
    value: https://github.com/sdubois-tapdemo/newsletter/newsletter-subscription/cartographer
  serviceClaims:
  - name: db
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ClassClaim
      name: newsletter-db
  source:
    git:
      ref:
        branch: main
      url: https://github.com/sdubois-tapdemo/newsletter
    subPath: newsletter-subscription

