package tanzu.newsletter.subscription.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import tanzu.newsletter.subscription.model.Subscription;

import java.util.List;

@Repository
public interface SubscriptionRepository extends JpaRepository<Subscription, Long>{

	// add a method to sort by last name
	// generated by JPA
	// UDEMY Course: Spring Boot 3: Learn Spring 6, Spring Core, Spring REST, Spring MVC, Spring Security, Thymeleaf, JPA, Hibernate, MySQL - Chapter 225
	// https://docs.spring.io/spring-data/jpa/reference/jpa/query-methods.html - JPA Query Methods
	public List<Subscription> findAllByOrderByLastNameAsc();
}
